from __future__ import annotations

from typing import Any

PANEL_CLASSIFICATION_SCHEMA: dict[str, Any] = {
    "type": "object",
    "additionalProperties": False,
    "required": [
        "panel_relevance",
        "extraction_decision",
        "application_task",
        "assay",
        "metric_category",
        "panel_type",
        "panel_role",
        "evidence_role",
        "matched_target_group_ids",
        "allowed_metrics",
        "allowed_units",
        "expected_value_types",
        "needs_digitization",
        "digitization_reason",
        "exclusion_reason",
        "expected_metric_fields",
        "recommended_metric_set",
        "main_entities",
        "visible_modalities",
        "ontology_terms",
        "why_relevant",
        "confidence",
    ],
    "properties": {
        "panel_relevance": {"type": "string", "enum": ["benchmark_metric", "supporting_observation", "context_only", "unusable"]},
        "extraction_decision": {"type": "string", "enum": ["extract_target_metrics", "extract_supporting_observation", "skip_metric_extraction"]},
        "application_task": {"type": "string"},
        "assay": {"type": "string"},
        "metric_category": {"type": "string"},
        "panel_type": {"type": "string"},
        "panel_role": {"type": "string"},
        "evidence_role": {"type": "string", "enum": ["primary_metric_panel", "supporting_observation", "schematic_context", "methods_context", "unusable"]},
        "matched_target_group_ids": {"type": "array", "items": {"type": "string"}},
        "allowed_metrics": {"type": "array", "items": {"type": "string"}},
        "allowed_units": {"type": "array", "items": {"type": "string"}},
        "expected_value_types": {"type": "array", "items": {"type": "string"}},
        "needs_digitization": {"type": "boolean"},
        "digitization_reason": {"type": "string"},
        "exclusion_reason": {"type": "string"},
        "expected_metric_fields": {"type": "array", "items": {"type": "string"}},
        "recommended_metric_set": {"type": "array", "items": {"type": "string"}},
        "main_entities": {"type": "object"},
        "visible_modalities": {"type": "object"},
        "ontology_terms": {"type": "object"},
        "evidence_links": {"type": "array", "items": {"type": "string"}},
        "paper_task_gap_candidate": {"type": "boolean"},
        "why_relevant": {"type": "string"},
        "confidence": {"type": "number"},
    },
}

